$pdf_previewer = "xdg-open";

$out_dir = "build";

$pdflatex = "pdflatex -interaction=nonstopmode -halt-on-error %O %S";
$lualatex = "lualatex -interaction=nonstopmode -halt-on-error %O %S";

# use lualatex
$pdf_mode = 4;

add_cus_dep('glo', 'gls', 0, 'makeglossaries');
sub makeglossaries {
   $dir = dirname($_[0]);
   $file = basename($_[0]);
   system( "makeglossaries", "-d", $dir, $file);
}

push @generated_exts, "bcf bbl";
$clean_ext = "bcf bbl glg glo gls run.xml xdy snm nav";
